name: CompileTesting

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Select architecture'
        required: true
        type: choice
        options:
          - all
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_vfpv3-d16
          - arm_cortex-a9_neon
          - arm_cortex-a15_neon-vfpv4
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_cortex-a76
          - aarch64_generic
          - i386_pentium4
          - x86_64
        default: 'all'
      openwrt_branch:
        description: 'Select OpenWrt branch'
        required: true
        type: choice
        options:
          - all
          - openwrt-23.05
          - openwrt-24.10
        default: 'all'
      source_branch:
        description: 'Select source code branch'
        required: true
        type: choice
        options:
          - main
          - dev
          - noobs
        default: 'main'
      create_release:
        description: 'Create GitHub Release?'
        required: false
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ github.event_name == 'push' && fromJSON('["arm_cortex-a5_vfpv4","arm_cortex-a7_neon-vfpv4","arm_cortex-a8_vfpv3","arm_cortex-a9","arm_cortex-a9_vfpv3-d16","arm_cortex-a9_neon","arm_cortex-a15_neon-vfpv4","aarch64_cortex-a53","aarch64_cortex-a72","aarch64_cortex-a76","aarch64_generic","i386_pentium4","x86_64"]') || (github.event.inputs.arch == 'all' && fromJSON('["arm_cortex-a5_vfpv4","arm_cortex-a7_neon-vfpv4","arm_cortex-a8_vfpv3","arm_cortex-a9","arm_cortex-a9_vfpv3-d16","arm_cortex-a9_neon","arm_cortex-a15_neon-vfpv4","aarch64_cortex-a53","aarch64_cortex-a72","aarch64_cortex-a76","aarch64_generic","i386_pentium4","x86_64"]') || fromJSON(format('["{0}"]', github.event.inputs.arch))) }}
        branch: ${{ github.event_name == 'push' && fromJSON('["openwrt-23.05","openwrt-24.10"]') || (github.event.inputs.openwrt_branch == 'all' && fromJSON('["openwrt-23.05","openwrt-24.10"]') || fromJSON(format('["{0}"]', github.event.inputs.openwrt_branch))) }}
        exclude:
          - arch: aarch64_cortex-a76
            branch: openwrt-23.05

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.source_branch || github.ref }}

      - name: free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: check build output
        run: |
          echo "Checking build output directory..."
          ls -la bin/packages/ || echo "bin/packages not found"
          ls -la bin/packages/${{ matrix.arch }}/ || echo "${{ matrix.arch }} directory not found"
          ls -la bin/packages/${{ matrix.arch }}/nikki/ || echo "nikki directory not found"

      - name: compress
        run: |
          if [ -d "bin/packages/${{ matrix.arch }}/nikki" ]; then
            tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C bin/packages/${{ matrix.arch }}/nikki .
          else
            echo "Error: nikki directory not found, creating empty archive"
            mkdir -p temp_dir
            echo "Build failed for ${{ matrix.arch }}-${{ matrix.branch }}" > temp_dir/build_failed.txt
            tar -c -z -f nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz -C temp_dir .
          fi

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: nikki_${{ matrix.arch }}-${{ matrix.branch }}.tar.gz

  release:
    needs: build
    name: create release
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && startsWith(github.ref_name, 'v')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.source_branch || github.ref }}

      - name: get version from makefile
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ -f "luci-app-nikki/Makefile" ]; then
              VERSION=$(grep -E '^PKG_VERSION\s*:?=' luci-app-nikki/Makefile | head -1 | cut -d'=' -f2 | tr -d ' ')
            fi
            if [ -z "$VERSION" ]; then
              VERSION="1.2.3"
            fi
            if [[ ! "$VERSION" =~ ^v ]]; then
              VERSION="v$VERSION"
            fi
            echo "tag_name=$VERSION" >> $GITHUB_OUTPUT
            echo "release_name=$VERSION" >> $GITHUB_OUTPUT
            echo "source_branch=${{ github.event.inputs.source_branch }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "release_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "source_branch=main" >> $GITHUB_OUTPUT
          fi

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: nikki_*
          merge-multiple: true

      - name: list downloaded files
        run: |
          echo "Downloaded files:"
          ls -la nikki_*.tar.gz

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: nikki_*.tar.gz
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: ${{ steps.version.outputs.tag_name }}
          draft: false
          body: |
            Nikki Mod ${{ steps.version.outputs.tag_name }}
            
            OpenWrt | snapshot Versions Support:
            - openwrt-23.05
            - openwrt-24.10
            - snapshot-latest
            
            Download the package for your device architecture and OpenWrt version.
